# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_fn_compute_NMA_comparisons <- function(trace_gq_vec, trace_dims, Se_indices_list, Sp_indices_list, n_thr) {
    .Call('_MetaOrdDTA_Rcpp_fn_compute_NMA_comparisons', PACKAGE = 'MetaOrdDTA', trace_gq_vec, trace_dims, Se_indices_list, Sp_indices_list, n_thr)
}

Rcpp_fn_compute_NMA_performance <- function(trace_gq_vec, trace_dims, Se_indices_list, Sp_indices_list, n_thr) {
    .Call('_MetaOrdDTA_Rcpp_fn_compute_NMA_performance', PACKAGE = 'MetaOrdDTA', trace_gq_vec, trace_dims, Se_indices_list, Sp_indices_list, n_thr)
}

